// SOMA — Habits library + per-habit metadata.
// Each habit can carry: lab/sub/icon (display), why (motivation),
// examples[] (suggestions), norepeat (anti-stagnation flag).
//
// "norepeat: true" means: doing the SAME exact thing as a recent entry
// doesn't count. Forces variation — core to callus-the-mind etc.

const HABITS = [
  // ── BODY & MOVEMENT ──
  { id: 'mobility',    cat: 'body',   lab: 'Daily mobility',
    sub: '10 min · long-hold stretches', icon: 'balance',
    why: 'Joint centration and tissue capacity prevent injury and unlock harder training.',
    examples: ['Couch stretch 2 min/side', 'Pigeon hold 90s/side',
      'Wall ankle dorsiflexion', 'Thoracic foam roll', 'Lat hang 60s',
      'Hip 90/90 flow', 'Banded shoulder dislocates'] },
  { id: 'cold',        cat: 'body',   lab: 'Cold plunge',
    sub: 'Morning · norepinephrine spike', icon: 'water',
    why: 'Spikes dopamine and norepinephrine, builds stress tolerance.',
    examples: ['Cold shower 3 min', 'Plunge 14°C · 2 min',
      'Cold lake swim', 'Outdoor cold immersion in winter clothes'] },
  { id: 'sauna',       cat: 'body',   lab: 'Sauna',
    sub: 'Heat shock proteins · recovery', icon: 'flame',
    why: 'Heat shock proteins · cardiovascular adaptation · recovery.',
    examples: ['20 min @ 80°C', 'Sauna-cold-sauna contrast',
      'Steam room 15 min'] },
  { id: 'grip',        cat: 'body',   lab: 'Grip strength check',
    sub: 'CNS readiness gauge', icon: 'dumbbell',
    why: 'A >5% drop from your best score = CNS fatigued. Tells you to back off.',
    examples: ['Dynamometer 3 reps both hands', 'Plate pinch 30s timed',
      'Dead hang max time'] },
  { id: 'walk',        cat: 'body',   lab: 'Outdoor walk',
    sub: 'Zone 2 · sunlight', icon: 'sun',
    why: 'Zone 2 cardio + sunlight + decompression all in one.',
    examples: ['45-min walk after lunch', 'Morning walk before phone',
      'Walking call', 'Park loop with friend'] },

  // ── MIND & RESILIENCE ──
  { id: 'callus',      cat: 'mind',   lab: 'Callus the mind',
    sub: 'One uncomfortable task', icon: 'flame',
    why: 'Inoculate against future trauma by voluntarily seeking discomfort. Builds an unshakeable baseline of discipline.',
    examples: [
      'Cold shower 3+ min',
      'Hard conversation you postponed',
      '5 min stillness · no phone',
      'A 16h+ fast',
      'A workout in your hated modality',
      'Difficult phone call you avoided',
      'Heavy lift you have been avoiding',
      'Pay an outstanding debt',
      'Public speaking moment',
      'Apologize to someone',
    ],
    norepeat: true },
  { id: 'stoic',       cat: 'mind',   lab: 'Dichotomy of control',
    sub: 'Stoic reflection', icon: 'balance',
    why: 'Separate what you control from what you don\'t. Shift locus from victim to agent.',
    examples: ['Name one thing you tried to control today that wasn\'t yours',
      'Name one thing you control and acted on',
      'Re-read morning quote'] },
  { id: 'meditate',    cat: 'mind',   lab: 'Meditation',
    sub: '10 min · still', icon: 'recovery',
    why: 'Default mode network reset. Reduces reactivity, improves focus.',
    examples: ['10 min breath count', '20 min body scan', 'Mantra repetition',
      'Open awareness', 'Walking meditation'] },
  { id: 'nsdr',        cat: 'mind',   lab: 'NSDR / Yoga Nidra',
    sub: 'Non-sleep deep rest', icon: 'moon',
    why: 'Recovers nervous system without sleep — replenishes dopamine reserves.',
    examples: ['20 min Yoga Nidra session', '10 min NSDR (Huberman)',
      'Reverie · 30 min stillness'] },
  { id: 'noscreen',    cat: 'mind',   lab: 'No phone first hour',
    sub: 'Dopamine reset', icon: 'recovery',
    why: 'Protects the early-day dopamine baseline. Sets reactive vs intentional tone.',
    examples: ['Phone in another room until coffee',
      'Airplane mode until 9am', 'No social media before workout'] },
  { id: 'gratitude',   cat: 'mind',   lab: 'Gratitude · 3 things',
    sub: 'Daily ritual', icon: 'heart',
    why: 'Trains attention to positive specifics. Compound effect over weeks.',
    examples: ['Write 3 things in journal',
      'Voice memo · 3 things specific to today',
      'Tell one person you appreciate them'] },
  { id: 'deepwork',    cat: 'mind',   lab: 'Deep work · 2hr block',
    sub: 'Time-blocked isolation', icon: 'bolt',
    why: 'Builds the capacity for high-output cognition. Phone away.',
    examples: ['2hr focused block · no Slack',
      '90 min Pomodoro stacked × 2',
      'Library session', 'No-meeting morning'] },

  // ── FUEL & BIOLOGY ──
  { id: 'hydrate',     cat: 'fuel',   lab: 'Hydration · 3L',
    sub: 'Water + electrolytes', icon: 'water',
    why: 'Mild dehydration impairs recovery, endurance and cognition.',
    examples: ['3L water + LMNT in morning',
      '1L before noon', 'Track ounces in app'] },
  { id: 'protein',     cat: 'fuel',   lab: 'Protein target',
    sub: 'Hit daily g', icon: 'protein',
    why: 'Limits muscle protein synthesis if under target. ~1.6-2.2 g/kg.',
    examples: ['Whey shake post-workout', '30g protein at breakfast',
      'Lean protein every meal'] },
  { id: 'noalcohol',   cat: 'fuel',   lab: 'No alcohol',
    sub: 'Sober streak', icon: 'water',
    why: 'Alcohol wrecks sleep architecture and recovery. Sober October-style streak.',
    examples: ['Decline every offer today', 'NA beer at dinner',
      'Stay home from drinking event'] },
  { id: 'greens',      cat: 'fuel',   lab: 'Greens · daily',
    sub: 'Probiotics + fiber', icon: 'carbs',
    why: 'Gut diversity supports immunity and mood via the gut-brain axis.',
    examples: ['Spinach in eggs', 'Side salad at lunch',
      'Greens powder', 'Sauerkraut spoonful'] },
  { id: 'sunlight',    cat: 'fuel',   lab: 'Morning sunlight',
    sub: '10 min · cortisol', icon: 'sun',
    why: 'Anchors circadian rhythm. 10 min of direct AM sun = better sleep tonight.',
    examples: ['Walk outside before coffee',
      'Coffee on the porch', 'Run before 8am'] },
  { id: 'fast',        cat: 'fuel',   lab: 'Intermittent fast',
    sub: '14-16 hr window', icon: 'timer',
    why: 'Autophagy + insulin sensitivity. Bonus mental clarity in fasted state.',
    examples: ['16:8 daily', 'OMAD weekly', 'Fasted workout'] },

  // ── SOCIAL & CONNECTION ──
  { id: 'connect',     cat: 'social', lab: 'Quality time · person',
    sub: 'Phone away', icon: 'heart',
    why: 'Connection moves more nervous-system needles than any supplement.',
    examples: ['Dinner with partner · no phones',
      'Call a friend who matters', 'Coffee with mentor',
      'Bedtime conversation'] },
  { id: 'boundary',    cat: 'social', lab: 'Set a boundary',
    sub: 'Say no when needed', icon: 'balance',
    why: 'Counter the People-Pleaser/Phlegmatic shadow. Protect your nervous system.',
    examples: ['Say no to a non-essential meeting',
      'Decline a favor that drains you',
      'Tell a friend "not today"'] },
  { id: 'service',     cat: 'social', lab: 'Act of service',
    sub: 'Help someone', icon: 'heart',
    why: 'Service flips internal narrative from "I lack" to "I have to give".',
    examples: ['Help a stranger', 'Cover for a colleague',
      'Mentor for 30 min'] },
];

const HABIT_CATS = [
  { id: 'body',   lab: 'Body',      color: 'train',   note: 'movement · hormesis' },
  { id: 'mind',   lab: 'Mind',      color: 'records', note: 'resilience · focus' },
  { id: 'fuel',   lab: 'Fuel',      color: 'eat',     note: 'inputs · biology' },
  { id: 'social', lab: 'Social',    color: 'journal', note: 'connection · service' },
];

// Mock history per habit. In production, this comes from user data.
// Each entry: { id, date, time, what }. Stored per habit-id.
const MOCK_HISTORY = {
  callus: [
    { id: 'h1', date: 'Tue', time: '07:30', what: 'Cold shower 3 min' },
    { id: 'h2', date: 'Mon', time: '14:00', what: 'Hard call with supplier' },
    { id: 'h3', date: 'Sat', time: '09:00', what: 'Cold shower 3 min' },
    { id: 'h4', date: 'Fri', time: '18:00', what: 'Long fast (18h)' },
  ],
  mobility: [
    { id: 'm1', date: 'Tue', time: '20:00', what: 'Couch stretch + pigeon' },
    { id: 'm2', date: 'Mon', time: '20:00', what: 'Couch stretch + pigeon' },
  ],
};

// Dynamic journal prompts — max 3 per day, drawn from frameworks.
const PROMPTS = [
  { id: 'somatic',  cat: 'Somatic',
    q: 'Where do you feel today\u2019s intensity in your body right now?' },
  { id: 'stoic',    cat: 'Stoic',
    q: 'What did you control today? What did you try to control that wasn\u2019t yours?' },
  { id: 'wound',    cat: 'Pattern',
    q: 'When did you decide to carry the weight alone — and why?' },
  { id: 'dopamine', cat: 'Dopamine',
    q: 'What activity was your brain magnetically drawn to today?' },
  { id: 'polarity', cat: 'Polarity',
    q: 'Was your day mostly logical execution or emotional flow?' },
  { id: 'feelgood', cat: 'Feel Good',
    q: 'What made today a "Feel Good Day" — even briefly?' },
  { id: 'pain',     cat: 'Body',
    q: 'Was today\u2019s discomfort, or pain? Where exactly?' },
  { id: 'energy',   cat: 'Energy',
    q: 'When did you feel most energized today? Least?' },
];

Object.assign(window, { HABITS, HABIT_CATS, MOCK_HISTORY, PROMPTS });
